# Generated by Django 5.1.2 on 2024-10-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
