# Generated by Django 5.1.2 on 2024-10-31 11:31

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=50, scale=None, size=[1920, 1080], upload_to='static/uploads/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=50, scale=None, size=[1920, 1080], upload_to='static/uploads/products'),
        ),
    ]
