# Generated by Django 5.1.2 on 2024-10-31 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_order_options_product_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
    ]
